telemetry:
  host: 127.0.0.1
  port: 6379
  database: 0
auto:
  name: Trench
  mode: collect_trench_powercells
auto_modes:
- name: Trench
  modes:
  - cross_initiation_line
  - collect_trench_powercells
- name: Goal
  modes:
  - score_trench
  - pickup_generator_score
- name: Mid
  modes:
  - score_pickup_generator
  - generator_pickup_score
