telemetry:
  host: 127.0.0.1
  port: 6379
  database: 0
auto:
  name: Home Trench
  mode: Trench Pickup Score
auto_modes:
- name: Away Trench
  modes:
  - collect_trench_powercells
  - cross_initiation_line
- name: Home  Trench
  modes:
  - trench_pickup_score
  - cross_initiation_line
- name: Goal
  modes:
  - score_trench
  - pickup_generator_score
  - cross_initiation_line
- name: Mid
  modes:
  - score_pickup_generator
  - generator_pickup_score
  - cross_initiation_line
